package MiCacharro;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class MiCacharro extends javax.swing.JFrame {

    public MiCacharro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoVehiculo = new javax.swing.ButtonGroup();
        panelTipoVehiculo = new javax.swing.JPanel();
        rbtAutomovil = new javax.swing.JRadioButton();
        rbtCamioneta = new javax.swing.JRadioButton();
        rbtCamion = new javax.swing.JRadioButton();
        panelCaracteristicas = new javax.swing.JPanel();
        cbCaracteristicas = new javax.swing.JComboBox<>();
        panelAccesorios = new javax.swing.JPanel();
        cbAccesorios = new javax.swing.JComboBox<>();
        panelAcciones = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MI CACHARRO: Presupuesto");

        panelTipoVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Vehículo"));

        grupoTipoVehiculo.add(rbtAutomovil);
        rbtAutomovil.setText("Automóvil");

        grupoTipoVehiculo.add(rbtCamioneta);
        rbtCamioneta.setText("Camioneta");

        grupoTipoVehiculo.add(rbtCamion);
        rbtCamion.setText("Camión");

        javax.swing.GroupLayout panelTipoVehiculoLayout = new javax.swing.GroupLayout(panelTipoVehiculo);
        panelTipoVehiculo.setLayout(panelTipoVehiculoLayout);
        panelTipoVehiculoLayout.setHorizontalGroup(
            panelTipoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoVehiculoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelTipoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtCamion)
                    .addComponent(rbtCamioneta)
                    .addComponent(rbtAutomovil))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelTipoVehiculoLayout.setVerticalGroup(
            panelTipoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtAutomovil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtCamioneta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtCamion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCaracteristicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Características"));

        cbCaracteristicas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Básico", "Semi Full", "Full Equipo" }));
        cbCaracteristicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCaracteristicasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCaracteristicasLayout = new javax.swing.GroupLayout(panelCaracteristicas);
        panelCaracteristicas.setLayout(panelCaracteristicasLayout);
        panelCaracteristicasLayout.setHorizontalGroup(
            panelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCaracteristicasLayout.setVerticalGroup(
            panelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbCaracteristicas.getAccessibleContext().setAccessibleName("Caracteristicas");

        panelAccesorios.setBorder(javax.swing.BorderFactory.createTitledBorder("Accesorios"));

        cbAccesorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Sin Accesorios", "Radio Básica", "Full Radio", "Full Radio+LCD TV", "Full Radio+LCD Full", "Full Radio+LCD Full+Llantas" }));
        cbAccesorios.setPreferredSize(new java.awt.Dimension(160, 20));
        cbAccesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAccesoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAccesoriosLayout = new javax.swing.GroupLayout(panelAccesorios);
        panelAccesorios.setLayout(panelAccesoriosLayout);
        panelAccesoriosLayout.setHorizontalGroup(
            panelAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccesoriosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(cbAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelAccesoriosLayout.setVerticalGroup(
            panelAccesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAccesoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cbAccesorios.getAccessibleContext().setAccessibleName("Accesorios");

        panelAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAccionesLayout = new javax.swing.GroupLayout(panelAcciones);
        panelAcciones.setLayout(panelAccionesLayout);
        panelAccionesLayout.setHorizontalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        panelAccionesLayout.setVerticalGroup(
            panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccionesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(panelAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelAccesorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelAccesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addComponent(panelAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        calcularPresupuesto(1);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        calcularPresupuesto(2);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        grupoTipoVehiculo.clearSelection();
        cbCaracteristicas.setSelectedIndex(0);
        cbAccesorios.setSelectedIndex(0);        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbCaracteristicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCaracteristicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCaracteristicasActionPerformed

    private void cbAccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAccesoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccesoriosActionPerformed

    public double calcularIVA(int valor) {
        double iva = 0.19;
        return (valor*iva);
    }
    
    
    public void calcularPresupuesto(int opcion) {
        DecimalFormat decimal = new DecimalFormat("###,###");
        int aPagar = 0;
        boolean swTipoVehiculo = true, swCaracteristicas = true, swAccesorios=true;
        String mensajeError = "Debe seleccionar:\n";
        String titulo="Error";
        
        String detalle = "Detalle de la compra\n";
        // verificando el tipo de vehículo
        if (rbtAutomovil.isSelected()) {
            aPagar += 5000000;
            detalle += "$ 5.000.000 - Automóvil\n";
            swTipoVehiculo = false;
        } else {
            if (rbtCamioneta.isSelected()) {
                aPagar += 8000000;
                detalle += "$ 8.000.000 - Camioneta\n";
                swTipoVehiculo = false;
            } else {
                if (rbtCamion.isSelected()) {
                    aPagar += 12000000;
                    detalle += "$ 12.000.000 - Camión\n";
                    swTipoVehiculo = false;
                } else {
                    // no ha seleccionado el tipo de vehículo
                    mensajeError += "- Tipo de Vehículo\n";
                }
            }
        }

        // verificando las características
        int Caracteristicas = cbCaracteristicas.getSelectedIndex();
        if (Caracteristicas > 0) {
            swCaracteristicas = false;
            switch (Caracteristicas) {
                case 1: {
                    // básico
                    aPagar += 0; // está demás
                    detalle += "$ 0 - Básico\n";
                    break;
                }
                case 2: {
                    // semi full
                    aPagar += 500000;
                    detalle += "$ 500.000 - Semi Full\n";
                    break;
                }
                case 3: {
                    // full equipo
                    aPagar += 1000000;
                    detalle += "$ 1.000.000 - Full Equipo\n";
                    break;
                }
            }
        } else {
            mensajeError += "- Características\n";
        }
        
        // verificando los accesorios
        int Accesorios = cbAccesorios.getSelectedIndex();
        if (Accesorios > 0) {
            swAccesorios = false;
            switch (Accesorios) {
                case 1: {
                    aPagar += 0;
                    detalle += "$ 0 - Sin accesorios\n";
                    break;
                }
                case 2: {
                    aPagar += 60000;
                    detalle += "$ 60.000 - Radio Básica\n";
                    break;
                }
                case 3: {
                    aPagar += 100000;
                    detalle += "$ 100.000 - Full Radio\n";
                    break;
                }
                case 4: {
                    aPagar += 150000;
                    detalle += "$ 150.000 - Full Radio + LCD TV\n";
                    break;
                }
                case 5: {
                    aPagar += 200000;
                    detalle += "$ 200.000 - Full Radio + LCD Full\n";
                    break;
                }
                case 6: { 
                    aPagar += 500000;
                    detalle += "$ 500.000 - Full Radio + LCD Full + Llantas\n";
                    break;
                }
            }
        } else {
            mensajeError += "- Accesorios\n";
        }
        double valorIVA = calcularIVA(aPagar);
        detalle += "$" + decimal.format(valorIVA)+ " - IVA"  + "\n";
        detalle += "\n$ " + decimal.format(aPagar * 1.19) + " - Total Presupuesto\n";

        if (swTipoVehiculo || swCaracteristicas || swAccesorios) {
            JOptionPane.showMessageDialog(null, mensajeError, titulo, JOptionPane.ERROR_MESSAGE);
        } else {
            if (opcion == 1) {
                JOptionPane.showMessageDialog(null, "Valor a Pagar $ " + decimal.format(aPagar * 1.19));
            } else {
                JOptionPane.showMessageDialog(null, detalle);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiCacharro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiCacharro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbAccesorios;
    private javax.swing.JComboBox<String> cbCaracteristicas;
    private javax.swing.ButtonGroup grupoTipoVehiculo;
    private javax.swing.JPanel panelAccesorios;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelCaracteristicas;
    private javax.swing.JPanel panelTipoVehiculo;
    private javax.swing.JRadioButton rbtAutomovil;
    private javax.swing.JRadioButton rbtCamion;
    private javax.swing.JRadioButton rbtCamioneta;
    // End of variables declaration//GEN-END:variables
}
